# Dockerfile/Docker-Compose file based on an initial version authored by Alexander Lontke (ASSE, Fall Semester 2021)

version: "3.7"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: tapas-fs22-group3-app
    # Use environment variables instead of application.properties
    environment:
     - KEY=VALUE
    ports: #Just needed when testing from outside the docker network
     - "8080:8080"
    networks:
      - tapas-network

  tapas-tasks:
    build:
      context: ./tapas-tasks
      dockerfile: Dockerfile-local
    image: tapas-fs22-group3-tapas-tasks
    # Use environment variables instead of application.properties
    environment:
      - KEY=VALUE
    hostname: tapas-tasks
    depends_on:
      - mongodb
    ports: #Just needed when testing from outside
      - "8086:8086"
    networks:
      - tapas-network

  tapas-executorpool:
    build:
      context: ./tapas-executorpool
      dockerfile: Dockerfile-local
    image: tapas-fs22-group3-tapas-executorpool
    # Use environment variables instead of application.properties
    environment:
      - KEY=VALUE
    ports: #Just needed when testing from outside
      - "8082:8082"
    depends_on:
      - mongodb
    hostname: tapas-executorpool
    networks:
      - tapas-network


  executor-compute:
    build:
      context: ./executor-compute
      dockerfile: Dockerfile-local
    image: tapas-fs22-group3-executor-compute
    # Use environment variables instead of application.properties
    environment:
      - KEY=VALUE
    ports: #Just needed when testing from outside
      - "8083:8083"
    networks:
      - tapas-network


  executor-api:
    build:
      context: ./executor-api
      dockerfile: Dockerfile-local
    image: tapas-fs22-group3-executor-api
    # Use environment variables instead of application.properties
    environment:
      - KEY=VALUE
    ports: #Just needed when testing from outside
      - "8084:8084"
    networks:
      - tapas-network

  tapas-roster:
    hostname: tapas-roster
    build:
      context: ./tapas-roster
      dockerfile: Dockerfile-local
    image: tapas-fs22-group3-tapas-roster
    # Use environment variables instead of application.properties
    environment:
      - KEY=VALUE
    ports: #Just needed when testing from outside
      - "8085:8085"
    depends_on:
      - mongodb
    networks:
      - tapas-network

  mongodb:
    image: mongo
    hostname: mongodb
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 8nP7s0a    # Can not be changed again later on
    volumes:
      - database:/data/db
    networks:
      - tapas-network

  dbadmin:
    image: mongo-express
    container_name: dbadmin
    restart: unless-stopped
    ports:
      - "8089:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: student    # Access to web interface: username
      ME_CONFIG_BASICAUTH_PASSWORD: studious   # Access to web interface: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 8nP7s0a  # must correspond to the db
      ME_CONFIG_MONGODB_PORT: 27017 # Default 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - tapas-network

#Volume for mongodb. One per server.
volumes:
  database:

networks:
  tapas-network:
    driver: bridge
