# Dockerfile/Docker-Compose file based on an initial version authored by Alexander Lontke (ASSE, Fall Semester 2021)

version: "3.7"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    # Use environment variables instead of application.properties
    environment:
     - KEY=VALUE
    ports: #Just needed when testing from outside the docker network
     - "8080:8080"    
    networks:
      - tapas-network

  tapas-tasks:
    build:
      context: ./tapas-tasks
      dockerfile: Dockerfile-local
    # Use environment variables instead of application.properties
    environment:
      - KEY=VALUE
    ports: #Just needed when testing from outside
      - "8081:8081"
    networks:
      - tapas-network
  tapas-executorpool:
    build:
      context: ./tapas-executorpool
      dockerfile: Dockerfile-local
    # Use environment variables instead of application.properties
    environment:
      - KEY=VALUE
    ports: #Just needed when testing from outside
      - "8082:8082"
    networks:
      - tapas-network


  executor-compute:
    build:
      context: ./executor-compute
      dockerfile: Dockerfile-local
    # Use environment variables instead of application.properties
    environment:
      - KEY=VALUE
    ports: #Just needed when testing from outside
      - "8083:8083"
    networks:
      - tapas-network


  executor-joke:
    build:
      context: ./executor-joke
      dockerfile: Dockerfile-local
    # Use environment variables instead of application.properties
    environment:
      - KEY=VALUE
    ports: #Just needed when testing from outside
      - "8083:8083"
    networks:
      - tapas-network

networks:
  tapas-network:
    driver: bridge
