# Dockerfile/Docker-Compose file based on an initial version authored by Alexander Lontke (ASSE, Fall Semester 2021)

FROM maven as build

COPY . /executor-joke

RUN mvn -f executor-joke/pom.xml --batch-mode --update-snapshots verify

FROM openjdk

COPY --from=build /executor-joke/target/executor-joke-0.0.1.jar ./executor-joke-0.0.1.jar

COPY --from=build /executor-joke/src/main/resources/application-local.properties ./application-local.properties

CMD java -jar executor-joke-0.0.1.jar --spring.config.location=application-local.properties
