# Dockerfile/Docker-Compose file based on an initial version authored by Alexander Lontke (ASSE, Fall Semester 2021)

FROM maven as build

COPY . /tapas-executorpool

RUN mvn -f tapas-executorpool/pom.xml --batch-mode --update-snapshots verify

FROM openjdk

COPY --from=build /tapas-executorpool/target/tapas-tasks-0.0.1.jar ./tapas-executorpool-0.0.1.jar

COPY --from=build /tapas-executorpool/src/main/resources/application-local.properties ./application-local.properties

CMD java -jar tapas-executorpool-0.0.1.jar --spring.config.location=application-local.properties
