# Dockerfile/Docker-Compose file based on an initial version authored by Alexander Lontke (ASSE, Fall Semester 2021)

FROM maven as build

COPY . /tapas-tasks

RUN mvn -f tapas-tasks/pom.xml --batch-mode --update-snapshots verify

FROM openjdk

COPY --from=build /tapas-tasks/target/tapas-tasks-0.0.1.jar ./tapas-tasks-0.0.1.jar

COPY --from=build /tapas-tasks/src/main/resources/application-local.properties ./application-local.properties

CMD java -jar tapas-tasks-0.0.1.jar --spring.config.location=application-local.properties
